apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
data:
  definitions.json: |
    {
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "users": [
        {
          "name": "lumie",
          "password_hash": "TSfR2onTI0QQvWMVUD2F3ZDjwSzppvMXKuZHsla+fcmzZJEC",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": ["administrator"]
        }
      ],
      "permissions": [
        {
          "user": "lumie",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "exchanges": [
        {
          "name": "lumie.commands",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false
        },
        {
          "name": "lumie.dlx",
          "vhost": "/",
          "type": "fanout",
          "durable": true,
          "auto_delete": false
        }
      ],
      "queues": [
        {
          "name": "grading.omr-request",
          "vhost": "/",
          "durable": true,
          "arguments": {
            "x-queue-type": "quorum",
            "x-dead-letter-exchange": "lumie.dlx",
            "x-message-ttl": 600000
          }
        },
        {
          "name": "grading.omr-request.dlq",
          "vhost": "/",
          "durable": true,
          "arguments": {
            "x-queue-type": "quorum"
          }
        },
        {
          "name": "grading.omr-completed",
          "vhost": "/",
          "durable": true,
          "arguments": {
            "x-queue-type": "quorum",
            "x-dead-letter-exchange": "lumie.dlx"
          }
        },
        {
          "name": "dlq.failed-messages",
          "vhost": "/",
          "durable": true,
          "arguments": {
            "x-queue-type": "quorum"
          }
        }
      ],
      "bindings": [
        {
          "source": "lumie.commands",
          "vhost": "/",
          "destination": "grading.omr-request",
          "destination_type": "queue",
          "routing_key": "grading.omr.request"
        },
        {
          "source": "lumie.dlx",
          "vhost": "/",
          "destination": "grading.omr-request.dlq",
          "destination_type": "queue",
          "routing_key": ""
        },
        {
          "source": "lumie.dlx",
          "vhost": "/",
          "destination": "dlq.failed-messages",
          "destination_type": "queue",
          "routing_key": ""
        }
      ]
    }
