apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zot-basic-auth-vss
spec:
  vaultAuthRef: vault/vault-auth
  mount: secret
  type: kv-v2
  path: infrastructure/zot
  refreshAfter: 1h
  destination:
    create: true
    name: teleport-app-basic-auth-zot
    transformation:
      excludeRaw: true
      templates:
        zot:
          text: 'Basic {{ printf "%s:%s" .Secrets.ZOT_USERNAME .Secrets.ZOT_PASSWORD | b64enc }}'
