# TLS Certificate for dev.lumie.lumie-infra.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lumie-dev-tls
  namespace: lumie-dev
spec:
  secretName: lumie-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - dev.lumie.lumie-infra.com
