apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: common
    releaseName: lumie-backend
    namespace: lumie-backend
    valuesFile: common-values.yaml
