apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: common
    releaseName: ai-svc
    namespace: lumie-ai
    valuesFile: common-values.yaml
