apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lumie-dev

resources:
  - ../../base

patches:
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    patch: |
      - op: replace
        path: /metadata/name
        value: rabbitmq-dev
  - target:
      kind: ConfigMap
      name: rabbitmq-definitions
    patch: |
      - op: replace
        path: /metadata/name
        value: rabbitmq-dev-definitions
  - target:
      kind: RabbitmqCluster
      name: rabbitmq-dev
    patch: |
      - op: replace
        path: /spec/override/statefulSet/spec/template/spec/volumes/0/configMap/name
        value: rabbitmq-dev-definitions
