apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-workspace-data
  namespace: dev-workspace
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-workspace-docker
  namespace: dev-workspace
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
