apiVersion: v1
kind: Service
metadata:
  name: dev-workspace
  namespace: dev-workspace
spec:
  type: ClusterIP
  selector:
    app: dev-workspace
  ports:
  - name: tilt-ui
    port: 10350
    targetPort: tilt-ui
    protocol: TCP
